-- MSU Main Campus course offerings and prospectus URLs imported from https://msu-prospectus.vercel.app/.
-- Run this after database/schema.sql in the Supabase SQL editor.
-- The app reads these rows from public.course_offerings; they are not hardcoded in the UI.

WITH imported_colleges (id, name, description) AS (
VALUES
  ('college-college-of-agriculture', 'College of Agriculture', 'Academic college or unit imported from the MSU Main Campus prospectus portal.'),
  ('college-college-of-business-administration-and-accountancy', 'College of Business Administration and Accountancy', 'Academic college or unit imported from the MSU Main Campus prospectus portal.'),
  ('college-college-of-education', 'College of Education', 'Academic college or unit imported from the MSU Main Campus prospectus portal.'),
  ('coe', 'College of Engineering', 'Academic college or unit imported from the MSU Main Campus prospectus portal.'),
  ('college-college-of-fisheries', 'College of Fisheries', 'Academic college or unit imported from the MSU Main Campus prospectus portal.'),
  ('college-college-of-forestry-and-environmental-studies', 'College of Forestry and Environmental Studies', 'Academic college or unit imported from the MSU Main Campus prospectus portal.'),
  ('chs', 'College of Health Sciences', 'Academic college or unit imported from the MSU Main Campus prospectus portal.'),
  ('chtm', 'College of Hospitality and Tourism Management', 'Academic college or unit imported from the MSU Main Campus prospectus portal.'),
  ('cics', 'College of Information and Computing Sciences', 'Academic college or unit imported from the MSU Main Campus prospectus portal.'),
  ('college-college-of-law', 'College of Law', 'Academic college or unit imported from the MSU Main Campus prospectus portal.'),
  ('college-college-of-medicine', 'College of Medicine', 'Academic college or unit imported from the MSU Main Campus prospectus portal.'),
  ('college-college-of-natural-sciences-and-mathematics', 'College of Natural Sciences and Mathematics', 'Academic college or unit imported from the MSU Main Campus prospectus portal.'),
  ('college-college-of-public-affairs', 'College of Public Affairs', 'Academic college or unit imported from the MSU Main Campus prospectus portal.'),
  ('college-college-of-social-sciences-and-humanities', 'College of Social Sciences and Humanities', 'Academic college or unit imported from the MSU Main Campus prospectus portal.'),
  ('college-college-of-sports-physical-education-and-recreation', 'College of Sports, Physical Education and Recreation', 'Academic college or unit imported from the MSU Main Campus prospectus portal.'),
  ('kfciaas', 'King Faisal Center for Islamic, Arabic and Asian Studies', 'Academic college or unit imported from the MSU Main Campus prospectus portal.')
),
updated_colleges AS (
  UPDATE public.colleges college
  SET description = imported.description
  FROM imported_colleges imported
  WHERE college.id = imported.id
    OR lower(college.name) = lower(imported.name)
  RETURNING college.id
)
INSERT INTO public.colleges (id, name, description)
SELECT imported.id, imported.name, imported.description
FROM imported_colleges imported
CROSS JOIN (SELECT count(*) FROM updated_colleges) updated_count
WHERE NOT EXISTS (
  SELECT 1
  FROM public.colleges college
  WHERE college.id = imported.id
    OR lower(college.name) = lower(imported.name)
);

WITH imported_courses (
  id,
  college_id,
  college,
  program,
  degree,
  overview,
  prospectus_url,
  tags
)
AS (
VALUES
  ('msu-bs-agriculture-major-in-agronomy', 'college-college-of-agriculture', 'College of Agriculture', 'BS Agriculture Major in Agronomy', 'BSA-AGRO', 'Advanced study of crop production, soil management, and sustainable farming systems tailored to the agro-climatic conditions of Mindanao and the Philippines.', 'https://msu-prospectus.vercel.app/msu-bsa-agro-prospectus.pdf', '["bsa-agro","college-college-of-agriculture","4 years","prospectus","agronomist","crop production specialist","agricultural researcher","plantation manager","farm consultant"]'::jsonb),
  ('msu-bs-agriculture-major-in-animal-science', 'college-college-of-agriculture', 'College of Agriculture', 'BS Agriculture Major in Animal Science', 'BSA-AS', 'Comprehensive training in livestock and poultry production, animal breeding, nutrition, and health management to boost food security in the region.', 'https://msu-prospectus.vercel.app/msu-bsa-as-prospectus.pdf', '["bsa-as","college-college-of-agriculture","4 years","prospectus","animal scientist","livestock farm manager","animal nutritionist","veterinary product consultant","technical consultant"]'::jsonb),
  ('msu-bs-agriculture-major-in-agricultural-extension', 'college-college-of-agriculture', 'College of Agriculture', 'BS Agriculture Major in Agricultural Extension', 'BSA-AEX', 'An intensive program designed to train professionals in agricultural education, community development, and rural leadership. It focuses on planning, implementing, and evaluating extension programs, tech-transfer methodologies, and peace-oriented community development across the MINSUPALA region.', 'https://msu-prospectus.vercel.app/COA/msu-bsa-aex-prospectus.pdf', '["bsa-aex","college-college-of-agriculture","4 years","prospectus","agricultural extension officer","farm consultant","community development organizer","rural development officer","agricultural journalist","program evaluator"]'::jsonb),
  ('msu-bs-agriculture-major-in-extension-education', 'college-college-of-agriculture', 'College of Agriculture', 'BS Agriculture Major in Extension Education', 'BSA-EXD', 'A curriculum focused on agricultural extension and communication, rural leadership, and community development. It trains students in extension teaching methods, adult education in agriculture, and extension program planning and evaluation to effectively support farming communities.', 'https://msu-prospectus.vercel.app/COA/msu-bsa-exd-prospectus.pdf', '["bsa-exd","college-college-of-agriculture","4 years","prospectus","agricultural extension officer","rural development specialist","community organizer","agricultural educator","agricultural communication consultant"]'::jsonb),
  ('msu-bs-agribusiness-management', 'college-college-of-agriculture', 'College of Agriculture', 'BS Agribusiness Management', 'BS-ABM', 'Integration of corporate business principles with agricultural sciences to manage agricultural value chains, enterprise development, and marketing.', 'https://msu-prospectus.vercel.app/COA/msu-bs-abm-prospectus.pdf', '["bs-abm","college-college-of-agriculture","4 years","prospectus","agribusiness manager","agricultural commodity trader","farm enterprise consultant","agricultural credit analyst","supply chain specialist"]'::jsonb),
  ('msu-bs-accountancy', 'college-college-of-business-administration-and-accountancy', 'College of Business Administration and Accountancy', 'BS Accountancy', 'BSA', 'Intensive training in financial accounting, auditing, taxation, and management advisory services, preparing students for the CPA licensure exam and global corporate practice.', 'https://msu-prospectus.vercel.app/msu-bsa-prospectus.pdf', '["bsa","college-college-of-business-administration-and-accountancy","4 years","prospectus","certified public accountant (cpa)","internal/external auditor","tax consultant","financial controller","chief financial officer (cfo)"]'::jsonb),
  ('msu-bsba-major-in-marketing-management', 'college-college-of-business-administration-and-accountancy', 'College of Business Administration and Accountancy', 'BSBA Major in Marketing Management', 'BSBA-MKT', 'Study of market dynamics, consumer behavior, brand management, and digital marketing strategies to drive business growth and competitive positioning.', 'https://msu-prospectus.vercel.app/msu-bsba-mkt-prospectus.pdf', '["bsba-mkt","college-college-of-business-administration-and-accountancy","4 years","prospectus","marketing manager","brand manager","market research analyst","sales executive","digital marketing strategist"]'::jsonb),
  ('msu-bsba-major-in-business-economics', 'college-college-of-business-administration-and-accountancy', 'College of Business Administration and Accountancy', 'BSBA Major in Business Economics', 'BSBA-ECON', 'Application of economic principles, quantitative analysis, and market theories to strategic corporate decision-making and economic policy analysis.', 'https://msu-prospectus.vercel.app/msu-bsba-econ-prospectus.pdf', '["bsba-econ","college-college-of-business-administration-and-accountancy","4 years","prospectus","business economist","financial analyst","market analyst","economic policy researcher","corporate planner"]'::jsonb),
  ('msu-bsba-major-in-human-resource-management', 'college-college-of-business-administration-and-accountancy', 'College of Business Administration and Accountancy', 'BSBA Major in Human Resource Management', 'BSBA-HR', 'Focuses on talent acquisition, strategic human resource planning, labor relations, performance management, and fostering organizational behavior excellence.', 'https://msu-prospectus.vercel.app/CBAA/msu-bsba-hr-prospectus.pdf', '["bsba-hr","college-college-of-business-administration-and-accountancy","4 years","prospectus","human resource manager","corporate recruiter","compensation and benefits specialist","training and development officer","labor relations officer"]'::jsonb),
  ('msu-master-in-business-administration', 'college-college-of-business-administration-and-accountancy', 'College of Business Administration and Accountancy', 'Master in Business Administration', 'MBA', 'Post-graduate program designed for professionals seeking advanced managerial competence, strategic leadership, and entrepreneurial innovation in diverse industries.', 'https://msu-prospectus.vercel.app/msu-mba-prospectus.pdf', '["mba","college-college-of-business-administration-and-accountancy","2 years","prospectus","executive director","corporate manager","chief executive officer (ceo)","management consultant","business entrepreneur"]'::jsonb),
  ('msu-bachelor-of-elementary-education', 'college-college-of-education', 'College of Education', 'Bachelor of Elementary Education', 'BEED', 'Professional teacher education program that equips students with pedagogical content knowledge, classroom management, and child development skills for primary schools.', 'https://msu-prospectus.vercel.app/msu-beed-prospectus.pdf', '["beed","college-college-of-education","4 years","prospectus","elementary school teacher","child development specialist","educational material developer","private tutor","school administrator"]'::jsonb),
  ('msu-bachelor-of-technology-and-livelihood-education', 'college-college-of-education', 'College of Education', 'Bachelor of Technology and Livelihood Education', 'BTLED', 'Prepares students to teach Technology and Livelihood Education (TLE) components in secondary education, including Home Economics, Industrial Arts, Agri-Fishery Arts, and Information and Communications Technology (ICT).', 'https://msu-prospectus.vercel.app/CED/msu-btled-prospectus.pdf', '["btled","college-college-of-education","4 years","prospectus","tle teacher","high school teacher","vocational instructor","livelihood program coordinator"]'::jsonb),
  ('msu-bachelor-of-secondary-education-major-in-mathematics', 'college-college-of-education', 'College of Education', 'Bachelor of Secondary Education Major in Mathematics', 'BSED-MATH', 'Prepares specialized secondary school educators by equipping them with rigorous foundational knowledge in advanced algebra, geometry, calculus, and statistics, combined with modern pedagogical strategies, classroom management, and instructional tools designed for 21st-century learners.', 'https://msu-prospectus.vercel.app/CED/msu-bsed-math-prospectus.pdf', '["bsed-math","college-college-of-education","4 years","prospectus","high school mathematics teacher","mathematics curriculum specialist","educational assessment officer","academic tutor","mathematics program coordinator"]'::jsonb),
  ('msu-bsed-major-in-english', 'college-college-of-education', 'College of Education', 'BSEd Major in English', 'BSED-ENG', 'Equips secondary school educators with comprehensive mastery of English language proficiency, literature, and second-language teaching methodologies.', 'https://msu-prospectus.vercel.app/msu-bsed-eng-prospectus.pdf', '["bsed-eng","college-college-of-education","4 years","prospectus","high school english teacher","esl instructor","language program coordinator","curriculum designer","textbook writer"]'::jsonb),
  ('msu-bsed-major-in-mathematics', 'college-college-of-education', 'College of Education', 'BSEd Major in Mathematics', 'BSED-MATH', 'Prepares specialized educators for secondary mathematics, covering advanced algebra, geometry, calculus, and mathematical pedagogical tools.', 'https://msu-prospectus.vercel.app/msu-bsed-math-prospectus.pdf', '["bsed-math","college-college-of-education","4 years","prospectus","high school math teacher","mathematics curriculum specialist","educational assessment officer","academic tutor"]'::jsonb),
  ('msu-bsed-major-in-science', 'college-college-of-education', 'College of Education', 'BSEd Major in Science', 'BSED-SCI', 'Prepares secondary science teachers with a multi-disciplinary foundation in biology, chemistry, physics, and environmental sciences through inquiry-based instruction.', 'https://msu-prospectus.vercel.app/msu-bsed-sci-prospectus.pdf', '["bsed-sci","college-college-of-education","4 years","prospectus","secondary science teacher","science exhibit coordinator","laboratory instructor","science education consultant"]'::jsonb),
  ('msu-bsed-major-in-filipino', 'college-college-of-education', 'College of Education', 'BSEd Major in Filipino', 'BSED-FIL', 'Binibigyang-bihasa ang mga mag-aaral sa pagtuturo ng wikang Filipino at panitikan sa sekundaryang antas, kasabay ng pagtataguyod ng kultura at kapayapaan.', 'https://msu-prospectus.vercel.app/msu-bsed-fil-prospectus.pdf', '["bsed-fil","college-college-of-education","4 years","prospectus","guro sa filipino (mataas na paaralan)","manunulat sa wikang filipino","tagasalin","espesyalista sa kurikulum"]'::jsonb),
  ('msu-bsed-major-in-social-studies', 'college-college-of-education', 'College of Education', 'BSEd Major in Social Studies', 'BSED-SOC', 'Trains secondary school teachers in history, governance, sociology, and economics, emphasizing peace education and civic awareness in the MINSUPALA region.', 'https://msu-prospectus.vercel.app/msu-bsed-soc-prospectus.pdf', '["bsed-soc","college-college-of-education","4 years","prospectus","social studies teacher","civics coordinator","community education officer","history researcher"]'::jsonb),
  ('msu-master-of-arts-in-education', 'college-college-of-education', 'College of Education', 'Master of Arts in Education', 'MAED', 'Graduate level program focused on advanced curriculum development, educational philosophy, instructional leadership, and educational research methodologies.', 'https://msu-prospectus.vercel.app/msu-maed-prospectus.pdf', '["maed","college-college-of-education","2 years","prospectus","school principal","academic supervisor","curriculum consultant","higher education instructor","educational researcher"]'::jsonb),
  ('msu-phd-in-educational-management', 'college-college-of-education', 'College of Education', 'PhD in Educational Management', 'PHD-ED', 'Doctoral program for executive educational leaders, focusing on strategic institutional governance, macro-educational planning, and transformative policy formulation.', 'https://msu-prospectus.vercel.app/msu-phd-ed-prospectus.pdf', '["phd-ed","college-college-of-education","3-4 years","prospectus","university professor","school superintendent","higher education director","educational policy consultant","institutional researcher"]'::jsonb),
  ('msu-bs-civil-engineering', 'coe', 'College of Engineering', 'BS Civil Engineering', 'BSCE', 'Rigorous training in structural design, geotechnical engineering, water resource management, and transportation systems, aligned with national infrastructure goals.', 'https://msu-prospectus.vercel.app/COE/msu-bsce-prospectus.pdf', '["bsce","coe","4 years","prospectus","civil engineer","project manager","structural designer","site engineer","quantity surveyor","geotechnical consultant"]'::jsonb),
  ('msu-bs-mechanical-engineering', 'coe', 'College of Engineering', 'BS Mechanical Engineering', 'BSME', 'Comprehensive study of thermal sciences, fluid mechanics, machine design, and manufacturing processes for industrial plant operations and power generation.', 'https://msu-prospectus.vercel.app/msu-bsme-prospectus.pdf', '["bsme","coe","4 years","prospectus","mechanical engineer","hvac engineer","plant operations manager","automotive engineer","maintenance engineer"]'::jsonb),
  ('coe-bsee-2018', 'coe', 'College of Engineering', 'BS Electrical Engineering', 'BSEE', 'Focuses on electrical power systems, renewable energy integration, electrical machine design, control systems, and high-voltage transmission networks.', 'https://msu-prospectus.vercel.app/msu-bsee-prospectus.pdf', '["bsee","coe","4 years","prospectus","electrical engineer","power plant engineer","grid operations analyst","electrical design engineer","energy consultant"]'::jsonb),
  ('msu-bs-electronics-engineering', 'coe', 'College of Engineering', 'BS Electronics Engineering', 'BSECE', 'Covers telecommunications, microelectronics, signal processing, embedded systems, and digital network infrastructure for the modern tech industry.', 'https://msu-prospectus.vercel.app/msu-bsece-prospectus.pdf', '["bsece","coe","4 years","prospectus","electronics engineer","telecommunications engineer","network systems engineer","broadcast engineer","embedded systems developer"]'::jsonb),
  ('msu-bs-chemical-engineering', 'coe', 'College of Engineering', 'BS Chemical Engineering', 'BSCHE', 'Application of chemical, physical, and biological sciences to industrial manufacturing processes, waste treatment, and bioprocess engineering.', 'https://msu-prospectus.vercel.app/msu-bsche-prospectus.pdf', '["bsche","coe","4 years","prospectus","chemical engineer","process engineer","quality assurance manager","environmental engineer","plant design consultant"]'::jsonb),
  ('msu-bs-agricultural-and-biosystems-engineering', 'coe', 'College of Engineering', 'BS Agricultural and Biosystems Engineering', 'BSAE', 'Application of engineering principles to agricultural mechanization, soil and water conservation, irrigation systems, and post-harvest technology.', 'https://msu-prospectus.vercel.app/msu-bsae-prospectus.pdf', '["bsae","coe","4 years","prospectus","agricultural engineer","irrigation specialist","farm machinery designer","post-harvest technologist","environmental consultant"]'::jsonb),
  ('msu-diploma-in-construction-technology', 'coe', 'College of Engineering', 'Diploma in Construction Technology', 'DCT', 'Practical 2-year technical curriculum providing competencies in building construction, blue-print reading, site supervision, and safety management.', 'https://msu-prospectus.vercel.app/msu-dct-prospectus.pdf', '["dct","coe","2 years","prospectus","construction supervisor","site inspector","quantity estimator","construction safety officer","subcontractor"]'::jsonb),
  ('msu-diploma-in-electrical-technology', 'coe', 'College of Engineering', 'Diploma in Electrical Technology', 'DET', 'Two-year technical program covering industrial and residential wiring, electrical maintenance, motor controls, and troubleshooting.', 'https://msu-prospectus.vercel.app/msu-det-prospectus.pdf', '["det","coe","2 years","prospectus","industrial electrician","maintenance technician","electrical contractor","line technician","electrical inspector"]'::jsonb),
  ('msu-master-of-science-in-engineering', 'coe', 'College of Engineering', 'Master of Science in Engineering', 'MS-ENG', 'Advanced research-driven post-graduate program specializing in modern engineering solutions, technological innovations, and complex systems analysis.', 'https://msu-prospectus.vercel.app/msu-ms-eng-prospectus.pdf', '["ms-eng","coe","2 years","prospectus","senior research engineer","engineering faculty","project consultant","technology development director"]'::jsonb),
  ('msu-bs-fisheries', 'college-college-of-fisheries', 'College of Fisheries', 'BS Fisheries', 'BSF', 'Comprehensive study of sustainable aquaculture, marine resource conservation, post-harvest fish processing, and capture fisheries management.', 'https://msu-prospectus.vercel.app/msu-bsf-prospectus.pdf', '["bsf","college-college-of-fisheries","4 years","prospectus","fisheries technologist","aquaculture farm manager","aquatic biologist","quality control inspector","fishery extension officer"]'::jsonb),
  ('msu-diploma-in-aquaculture', 'college-college-of-fisheries', 'College of Fisheries', 'Diploma in Aquaculture', 'D-AQUA', 'Two-year hands-on technical program focusing on fish hatchery operations, pond management, feeding techniques, and aquatic health care.', 'https://msu-prospectus.vercel.app/msu-d-aqua-prospectus.pdf', '["d-aqua","college-college-of-fisheries","2 years","prospectus","aquaculture technician","hatchery supervisor","fish farm operations assistant","technical extensionist"]'::jsonb),
  ('msu-bs-forestry', 'college-college-of-forestry-and-environmental-studies', 'College of Forestry and Environmental Studies', 'BS Forestry', 'BS-FOR', 'Focused on sustainable forest ecosystem management, watershed conservation, agroforestry practices, and environmental policy implementation.', 'https://msu-prospectus.vercel.app/msu-bs-for-prospectus.pdf', '["bs-for","college-college-of-forestry-and-environmental-studies","4 years","prospectus","registered forester","forest conservationist","watershed manager","environmental consultant","denr officer"]'::jsonb),
  ('msu-bs-environmental-science', 'college-college-of-forestry-and-environmental-studies', 'College of Forestry and Environmental Studies', 'BS Environmental Science', 'BS-ES', 'Multi-disciplinary analysis of ecological issues, climate change mitigation, environmental impact assessments, and biodiversity preservation in Mindanao.', 'https://msu-prospectus.vercel.app/msu-bs-es-prospectus.pdf', '["bs-es","college-college-of-forestry-and-environmental-studies","4 years","prospectus","environmental scientist","ecotourism officer","environmental impact analyst","conservation officer","sustainability coordinator"]'::jsonb),
  ('msu-bs-nursing', 'chs', 'College of Health Sciences', 'BS Nursing', 'BSN', 'Premier professional healthcare education program emphasizing clinical competence, community health, and transcultural nursing care in diverse communities.', 'https://msu-prospectus.vercel.app/CHS/msu-bsn-prospectus.pdf', '["bsn","chs","4 years","prospectus","registered nurse","clinical nurse specialist","public health nurse","healthcare administrator","nurse educator"]'::jsonb),
  ('msu-bs-hospitality-management', 'chtm', 'College of Hospitality and Tourism Management', 'BS Hospitality Management', 'BSHM', 'Comprehensive education in lodging management, food and beverage operations, culinary management, and service operations excellence for the hospitality industry.', 'https://msu-prospectus.vercel.app/msu-bshm-prospectus.pdf', '["bshm","chtm","4 years","prospectus","hotel front office manager","restaurant owner/manager","catering director","guest relations manager","event planner"]'::jsonb),
  ('msu-bs-tourism-management', 'chtm', 'College of Hospitality and Tourism Management', 'BS Tourism Management', 'BSTM', 'Studies tourism destination planning, travel agency operations, heritage tourism promotion, and sustainable tourism policy and development.', 'https://msu-prospectus.vercel.app/msu-bstm-prospectus.pdf', '["bstm","chtm","4 years","prospectus","tourism officer","travel consultant","tour operator","airline customer service officer","destination marketing specialist"]'::jsonb),
  ('msu-diploma-in-culinary-arts', 'chtm', 'College of Hospitality and Tourism Management', 'Diploma in Culinary Arts', 'D-CUL', 'Two-year intensive professional training in culinary skills, international cuisines, pastry arts, food safety, and kitchen operations management.', 'https://msu-prospectus.vercel.app/msu-d-cul-prospectus.pdf', '["d-cul","chtm","2 years","prospectus","professional chef","sous chef","kitchen supervisor","caterer","pastry artisan","food stylist"]'::jsonb),
  ('msu-bs-computer-science', 'cics', 'College of Information and Computing Sciences', 'BS Computer Science', 'BSCS', 'Study of computing theory, complex algorithm design, artificial intelligence, software engineering methodologies, and advanced software system development.', 'https://msu-prospectus.vercel.app/CICS/msu-bscs-prospectus.pdf', '["bscs","cics","4 years","prospectus","software engineer","systems architect","ai developer","data scientist","full-stack software developer"]'::jsonb),
  ('cics-bsit-dbs', 'cics', 'College of Information and Computing Sciences', 'BS Information Technology Major in Database', 'BSIT-DB', 'Specialized IT track focusing on structural database administration, data warehousing, business intelligence, data modeling, and secure backend systems.', 'https://msu-prospectus.vercel.app/CICS/msu-bsit-database-prospectus.pdf', '["bsit-db","cics","4 years","prospectus","database administrator (dba)","database developer","data analyst","back-end developer","data security specialist"]'::jsonb),
  ('msu-bs-information-technology-major-in-networking', 'cics', 'College of Information and Computing Sciences', 'BS Information Technology Major in Networking', 'BSIT-NET', 'Advanced study of local and wide-area network architecture, cloud computing infrastructure, routing Protocols, and network cybersecurity operations.', 'https://msu-prospectus.vercel.app/CICS/msu-bsit-networking-prospectus.pdf', '["bsit-net","cics","4 years","prospectus","network administrator","cyber security analyst","cloud systems engineer","network infrastructure engineer","it support engineer"]'::jsonb),
  ('msu-bs-information-systems', 'cics', 'College of Information and Computing Sciences', 'BS Information Systems', 'BSIS', 'Blends information technology solutions with corporate organizational management to design, implement, and optimize business enterprise workflows.', 'https://msu-prospectus.vercel.app/CICS/msu-bsis-prospectus.jpg', '["bsis","cics","4 years","prospectus","business systems analyst","it project manager","enterprise resource planning (erp) consultant","digital transformation specialist"]'::jsonb),
  ('msu-juris-doctor-law', 'college-college-of-law', 'College of Law', 'Juris Doctor (Law)', 'JD', 'Comprehensive post-graduate legal education focusing on constitutional, civil, criminal, and corporate law, emphasizing human rights and alternate dispute resolution.', 'https://msu-prospectus.vercel.app/msu-jd-prospectus.pdf', '["jd","college-college-of-law","4 years","prospectus","lawyer","legal counsel","judge","prosecutor","arbitrator","legal consultant","public defender"]'::jsonb),
  ('msu-doctor-of-medicine', 'college-college-of-medicine', 'College of Medicine', 'Doctor of Medicine', 'MD', 'Elite medical training integrating biomedical sciences, clinical diagnostics, surgery, and community-oriented healthcare delivery for the underserved.', 'https://msu-prospectus.vercel.app/msu-md-prospectus.pdf', '["md","college-college-of-medicine","4 years","prospectus","licensed physician","clinical specialist","medical researcher","hospital administrator","public health medical officer"]'::jsonb),
  ('msu-bs-biology-major-in-animal-biology', 'college-college-of-natural-sciences-and-mathematics', 'College of Natural Sciences and Mathematics', 'BS Biology Major in Animal Biology)', 'BS-BIO', 'Intensive study of zoology, comparative anatomy, physiology, and evolutionary biology, preparing students for medical school or ecological research.', 'https://msu-prospectus.vercel.app/CNSM/msu-bs-bio-prospectus.pdf', '["bs-bio","college-college-of-natural-sciences-and-mathematics","4 years","prospectus","biologist","wildlife researcher","zoologist","laboratory analyst","pre-med candidate","environmental consultant"]'::jsonb),
  ('msu-bs-chemistry', 'college-college-of-natural-sciences-and-mathematics', 'College of Natural Sciences and Mathematics', 'BS Chemistry', 'BS-CHEM', 'In-depth exploration of analytical, organic, inorganic, and physical chemistry, preparing professional chemists for laboratory research and industry testing.', 'https://msu-prospectus.vercel.app/msu-bs-chem-prospectus.pdf', '["bs-chem","college-college-of-natural-sciences-and-mathematics","4 years","prospectus","licensed chemist","quality control analyst","laboratory manager","research \u0026 development scientist","forensic chemist"]'::jsonb),
  ('msu-bs-mathematics', 'college-college-of-natural-sciences-and-mathematics', 'College of Natural Sciences and Mathematics', 'BS Mathematics', 'BS-MATH', 'Rigid program emphasizing theoretical mathematics, statistical modeling, advanced calculus, and mathematical research techniques for real-world application.', 'https://msu-prospectus.vercel.app/msu-bs-math-prospectus.pdf', '["bs-math","college-college-of-natural-sciences-and-mathematics","4 years","prospectus","mathematician","actuarial analyst","data scientist","statistical researcher","financial risk analyst"]'::jsonb),
  ('msu-bs-physics', 'college-college-of-natural-sciences-and-mathematics', 'College of Natural Sciences and Mathematics', 'BS Physics', 'BS-PHYS', 'Foundations of classical and quantum mechanics, electromagnetism, optics, and solid-state physics with strong mathematical and experimental components.', 'https://msu-prospectus.vercel.app/msu-bs-phys-prospectus.pdf', '["bs-phys","college-college-of-natural-sciences-and-mathematics","4 years","prospectus","research physicist","materials scientist","data analyst","laboratory researcher","optical engineer"]'::jsonb),
  ('msu-master-of-science-in-biology', 'college-college-of-natural-sciences-and-mathematics', 'College of Natural Sciences and Mathematics', 'Master of Science in Biology', 'MS-BIO', 'Advanced post-graduate thesis program enabling specialized independent research in ecology, genetics, physiology, and molecular biology.', 'https://msu-prospectus.vercel.app/msu-ms-bio-prospectus.pdf', '["ms-bio","college-college-of-natural-sciences-and-mathematics","2 years","prospectus","senior biological researcher","college professor","environmental impact consultant","biotech research director"]'::jsonb),
  ('msu-bs-social-work', 'college-college-of-public-affairs', 'College of Public Affairs', 'BS Social Work', 'BSSW', 'Prepares professionals for social change, community development, welfare program management, and psychosocial intervention in post-conflict and marginalized settings.', 'https://msu-prospectus.vercel.app/msu-bssw-prospectus.pdf', '["bssw","college-college-of-public-affairs","4 years","prospectus","registered social worker","case manager","community development officer","ngo project coordinator","medical social worker"]'::jsonb),
  ('msu-bachelor-of-public-administration', 'college-college-of-public-affairs', 'College of Public Affairs', 'Bachelor of Public Administration', 'BPA', 'Comprehensive education in governmental policy, public management, fiscal administration, and local governance accountability with an emphasis on ethics.', 'https://msu-prospectus.vercel.app/CPA/msu-bpa-prospectus.pdf', '["bpa","college-college-of-public-affairs","4 years","prospectus","public administration officer","local government analyst","policy researcher","human resource officer in public sector","civic leader"]'::jsonb),
  ('msu-master-of-public-administration', 'college-college-of-public-affairs', 'College of Public Affairs', 'Master of Public Administration', 'MPA', 'Post-graduate program for civil servants and organizational heads to refine administrative capacity, macro policy implementation, and ethical governance leadership.', 'https://msu-prospectus.vercel.app/msu-mpa-prospectus.pdf', '["mpa","college-college-of-public-affairs","2 years","prospectus","government bureau director","city/municipal administrator","public policy consultant","non-profit executive director"]'::jsonb),
  ('msu-doctor-of-public-administration', 'college-college-of-public-affairs', 'College of Public Affairs', 'Doctor of Public Administration', 'DPA', 'Executive doctoral degree focusing on strategic macro-level public policy evaluation, structural governance reforms, and academic research leadership.', 'https://msu-prospectus.vercel.app/msu-dpa-prospectus.pdf', '["dpa","college-college-of-public-affairs","3-4 years","prospectus","cabinet secretary advisor","university professor","senior policy analyst","governance consultant","international development specialist"]'::jsonb),
  ('msu-ba-psychology', 'college-college-of-social-sciences-and-humanities', 'College of Social Sciences and Humanities', 'BA Psychology', 'BA-PSYCH', 'Scientific investigation of cognitive processes, developmental psychology, industrial-organizational behavior, and counseling psychological assessment models.', 'https://msu-prospectus.vercel.app/msu-ba-psych-prospectus.pdf', '["ba-psych","college-college-of-social-sciences-and-humanities","4 years","prospectus","psychometrician","human resource professional","guidance associate","behavioral researcher","training specialist"]'::jsonb),
  ('msu-ba-political-science', 'college-college-of-social-sciences-and-humanities', 'College of Social Sciences and Humanities', 'BA Political Science', 'BA-POLSCI', 'Deep analysis of political systems, comparative governance, international relations, public law, and political theories, providing strong preparation for law school.', 'https://msu-prospectus.vercel.app/CSSH/msu-ba-polsci-prospectus.pdf', '["ba-polsci","college-college-of-social-sciences-and-humanities","4 years","prospectus","political analyst","policy researcher","legislative assistant","pre-law scholar","foreign service officer"]'::jsonb),
  ('msu-ba-sociology', 'college-college-of-social-sciences-and-humanities', 'College of Social Sciences and Humanities', 'BA Sociology', 'BA-SOCIO', 'Explores social structures, institutional dynamics, cultural transformations, and social issues, focusing on regional community diversity and peace studies.', 'https://msu-prospectus.vercel.app/msu-ba-socio-prospectus.pdf', '["ba-socio","college-college-of-social-sciences-and-humanities","4 years","prospectus","sociologist","social researcher","community organizer","corporate social responsibility specialist","cultural consultant"]'::jsonb),
  ('msu-ba-history', 'college-college-of-social-sciences-and-humanities', 'College of Social Sciences and Humanities', 'BA History', 'BA-HIST', 'Rigorous investigation of Philippine, Asian, and world history, with custom regional emphasis on the history and historical narratives of the MINSUPALA region.', 'https://msu-prospectus.vercel.app/msu-ba-hist-prospectus.pdf', '["ba-hist","college-college-of-social-sciences-and-humanities","4 years","prospectus","historian","archivist","historical consultant","researcher","museum curator","cultural heritage officer"]'::jsonb),
  ('msu-ba-english-language-studies', 'college-college-of-social-sciences-and-humanities', 'College of Social Sciences and Humanities', 'BA English Language Studies', 'BA-ELS', 'Advanced study of the English language, structural linguistics, socio-linguistics, and stylistic discourse to build professional language experts.', 'https://msu-prospectus.vercel.app/msu-ba-els-prospectus.pdf', '["ba-els","college-college-of-social-sciences-and-humanities","4 years","prospectus","linguist","content writer","editor","communications specialist","public relations officer","language researcher"]'::jsonb),
  ('msu-ba-journalism', 'college-college-of-social-sciences-and-humanities', 'College of Social Sciences and Humanities', 'BA Journalism', 'BA-JOURN', 'Professional training in journalism, broadcasting, and digital media, focusing on media''s role in social change, peacebuilding, and advocacy in the 21st-century global village.', 'https://msu-prospectus.vercel.app/CSSH/msu-ba-journalism-prospectus.pdf', '["ba-journ","college-college-of-social-sciences-and-humanities","4 years","prospectus","journalist","broadcaster","corporate communication officer","media practitioner","public service professional"]'::jsonb),
  ('msu-ba-communication', 'college-college-of-social-sciences-and-humanities', 'College of Social Sciences and Humanities', 'BA Communication', 'BA-COMM', 'Broad study of communication theory, public relations, audio-visual broadcasting, multi-media content creation, and institutional corporate communications.', 'https://msu-prospectus.vercel.app/CSSH/msu-ba-comm-prospectus.pdf', '["ba-comm","college-college-of-social-sciences-and-humanities","4 years","prospectus","media practitioner","public relations specialist","corporate communication manager","broadcaster","content producer"]'::jsonb),
  ('msu-bs-development-communication', 'college-college-of-social-sciences-and-humanities', 'College of Social Sciences and Humanities', 'BS Development Communication', 'BS-DEVCOM', 'Studies the use of communication media and strategies to advance societal development, environmental sustainability, peace journalism, and community empowerment.', 'https://msu-prospectus.vercel.app/CSSH/msu-bs-devcom-prospectus.pdf', '["bs-devcom","college-college-of-social-sciences-and-humanities","4 years","prospectus","development communicator","community organizer","public information officer","ngo worker","communication researcher"]'::jsonb),
  ('msu-ba-philosophy', 'college-college-of-social-sciences-and-humanities', 'College of Social Sciences and Humanities', 'BA Philosophy', 'BA-PHILO', 'Intensive engagement with logic, epistemology, ethics, social-political philosophy, and critical thinking paradigms, ideal for pre-law preparation.', 'https://msu-prospectus.vercel.app/CSSH/msu-ba-philosophy-prospectus.pdf', '["ba-philo","college-college-of-social-sciences-and-humanities","4 years","prospectus","philosophy professor","policy advisor","ethics consultant","researcher","pre-law scholar"]'::jsonb),
  ('msu-bachelor-of-physical-education', 'college-college-of-sports-physical-education-and-recreation', 'College of Sports, Physical Education and Recreation', 'Bachelor of Physical Education', 'BPED', 'Training in kinesiology, physical fitness pedagogy, sports mechanics, coaching frameworks, and management of local and institutional athletic events.', 'https://msu-prospectus.vercel.app/msu-bped-prospectus.pdf', '["bped","college-college-of-sports-physical-education-and-recreation","4 years","prospectus","physical education teacher","athletic coach","sports program administrator","fitness specialist","recreation director"]'::jsonb),
  ('msu-diploma-in-sports-coaching', 'college-college-of-sports-physical-education-and-recreation', 'College of Sports, Physical Education and Recreation', 'Diploma in Sports Coaching', 'D-SC', 'Practical 2-year vocational program providing training in sports psychology, athletic conditioning, sports rules, and team leadership strategies.', 'https://msu-prospectus.vercel.app/msu-d-sc-prospectus.pdf', '["d-sc","college-college-of-sports-physical-education-and-recreation","2 years","prospectus","athletic coach","assistant coach","fitness trainer","sports officiating official","community recreation specialist"]'::jsonb),
  ('msu-ba-islamic-studies', 'kfciaas', 'King Faisal Center for Islamic, Arabic and Asian Studies', 'BA Islamic Studies', 'BA-IS', 'Comprehensive study of Islamic jurisprudence (Fiqh), Islamic history, Quranic exegesis, Arabic theology, and contemporary Islamic socio-cultural thought.', 'https://msu-prospectus.vercel.app/KFCIAAS/msu-ba-is-prospectus.pdf', '["ba-is","kfciaas","4 years","prospectus","islamic scholar","shari\u0027ah law consultant","religious educator","cultural affairs officer","halal industry advisor"]'::jsonb),
  ('msu-bs-islamic-banking-and-finance', 'college-college-of-business-administration-and-accountancy', 'College of Business Administration and Accountancy', 'BS Islamic Banking and Finance', 'BS-IBF', 'Integrates core banking and finance principles with modern Islamic economics, Shari''ah compliance laws, and ethical financial management practices.', 'https://msu-prospectus.vercel.app/KFCIAAS/msu-bs-ibf-prospectus.pdf', '["bs-ibf","college-college-of-business-administration-and-accountancy","4 years","prospectus","shari\u0027ah compliance officer","islamic bank branch manager","financial analyst","takaful (islamic insurance) specialist","islamic investment consultant"]'::jsonb),
  ('msu-ba-arabic-language', 'kfciaas', 'King Faisal Center for Islamic, Arabic and Asian Studies', 'BA Arabic Language', 'BA-ARABIC', 'Specialized mastery of classical and modern standard Arabic linguistics, text translation, speech articulation, and literature interpretation.', 'https://msu-prospectus.vercel.app/msu-ba-arabic-prospectus.pdf', '["ba-arabic","kfciaas","4 years","prospectus","arabic-english translator","interpreter","middle east liaison officer","arabic language educator","foreign service specialist"]'::jsonb),
  ('msu-ba-international-relations', 'kfciaas', 'King Faisal Center for Islamic, Arabic and Asian Studies', 'BA International Relations', 'BA-IR', 'Global politics, international diplomacy, international law, and conflict resolution analysis, tailored with perspectives on regional peace networks.', 'https://msu-prospectus.vercel.app/msu-ba-ir-prospectus.pdf', '["ba-ir","kfciaas","4 years","prospectus","diplomat","foreign service officer","international analyst","global ngo coordinator","intelligence analyst"]'::jsonb),
  ('msu-master-of-arts-in-islamic-studies', 'kfciaas', 'King Faisal Center for Islamic, Arabic and Asian Studies', 'Master of Arts in Islamic Studies', 'MA-IS', 'Graduate level program focused on advanced research in Islamic thought, institutional governance, theology, and contemporary challenges facing Muslim societies.', 'https://msu-prospectus.vercel.app/msu-ma-is-prospectus.pdf', '["ma-is","kfciaas","2 years","prospectus","senior islamic researcher","university professor","islamic shari\u0027ah advisory consultant","public policy expert"]'::jsonb)
)
INSERT INTO public.course_offerings (
  id,
  college_id,
  college,
  program,
  degree,
  overview,
  prospectus_url,
  tags
)
SELECT
  course.id,
  COALESCE(college.id, course.college_id),
  course.college,
  course.program,
  course.degree,
  course.overview,
  course.prospectus_url,
  course.tags
FROM imported_courses course
LEFT JOIN public.colleges college
  ON lower(college.name) = lower(course.college)
ON CONFLICT (id) DO UPDATE SET
  college_id = EXCLUDED.college_id,
  college = EXCLUDED.college,
  program = EXCLUDED.program,
  degree = EXCLUDED.degree,
  overview = EXCLUDED.overview,
  prospectus_url = EXCLUDED.prospectus_url,
  tags = EXCLUDED.tags,
  updated_at = now();
