-- Official Academic Calendar, School Year 2025-2026.
-- Run this after database/schema.sql in the Supabase SQL editor.
-- The app reads these rows from public.academic_calendar; they are not hardcoded in the UI.

INSERT INTO public.academic_calendar (
  id,
  title,
  event_date,
  date_label,
  type,
  audience,
  details,
  table_activity,
  first_semester,
  second_semester,
  summer,
  table_highlight,
  table_section
)
VALUES
  ('cal-2025-2026-001', 'System Admission and Scholarship Examination (SASE) / Special College Entrance Test (CET)', NULL, 'Table view row', 'enrollment', 'MSU community', 'Official Academic Calendar, School Year 2025-2026.', 'System Admission and Scholarship Examination (SASE) / Special College Entrance Test (CET)', 'Per OVPAA & Adm. Schedule', 'Per OVPAA & Adm. Schedule', NULL, false, false),
  ('cal-2025-2026-002', 'Review/update the syllabus, assess student record status, and formulate a detailed semester plan', NULL, 'Table view row', 'event', 'Faculty', 'Official Academic Calendar, School Year 2025-2026.', 'Review/update the syllabus, assess student record status, and formulate a detailed semester plan', 'Mon, 21 Jul - Fri, 25 Jul', 'Mon, 05 Jan - Fri, 09 Jan', 'Mon, 01 Jun - Fri, 05 Jun', false, false),
  ('cal-2025-2026-003', 'Enrolment for Freshmen/New Students', NULL, 'Table view row', 'enrollment', 'Students', 'Official Academic Calendar, School Year 2025-2026.', 'Enrolment for Freshmen/New Students', 'Mon, 28 Jul - Fri, 01 Aug', 'Mon, 12 Jan - Fri, 16 Jan', NULL, false, false),
  ('cal-2025-2026-004', 'Enrolment for Old Students', NULL, 'Table view row', 'enrollment', 'Students', 'Official Academic Calendar, School Year 2025-2026.', 'Enrolment for Old Students', 'Mon, 04 Aug - Fri, 08 Aug', 'Mon, 19 Jan - Fri, 23 Jan', NULL, false, false),
  ('cal-2025-2026-005', 'Last Day for Validation of Enrollment and Billing Forms (EBF)', NULL, 'Table view row', 'deadline', 'Students', 'Official Academic Calendar, School Year 2025-2026.', 'Last Day for Validation of Enrollment and Billing Forms (EBF)', 'Mon, 11 Aug', 'Mon, 26 Jan', NULL, false, false),
  ('cal-2025-2026-006', 'Last Day for Changing Academic Status', NULL, 'Table view row', 'deadline', 'Students', 'Official Academic Calendar, School Year 2025-2026.', 'Last Day for Changing Academic Status', 'Mon, 11 Aug', 'Mon, 26 Jan', NULL, false, false),
  ('cal-2025-2026-007', 'START OF CLASSES', NULL, 'Table view row', 'classes', 'Students and faculty', 'Official Academic Calendar, School Year 2025-2026.', 'START OF CLASSES', 'Mon, 11 Aug', 'Mon, 26 Jan', 'Mon, 08 Jun', false, true),
  ('cal-2025-2026-008', 'Late Registration with Fines', NULL, 'Table view row', 'enrollment', 'Students', 'Official Academic Calendar, School Year 2025-2026.', 'Late Registration with Fines', 'Mon, 11 Aug - Fri, 15 Aug', 'Mon, 26 Jan - Fri, 30 Jan', NULL, false, false),
  ('cal-2025-2026-009', 'Change/Add Matriculation and Validation Period', NULL, 'Table view row', 'enrollment', 'Students', 'Official Academic Calendar, School Year 2025-2026.', 'Change/Add Matriculation and Validation Period', 'Mon, 11 Aug - Fri, 15 Aug', 'Mon, 26 Jan - Fri, 30 Jan', NULL, false, false),
  ('cal-2025-2026-010', 'Last Day for Submission of Completion Grades for INC Grades Incurred:', NULL, 'Table view row', 'deadline', 'Students', 'Official Academic Calendar, School Year 2025-2026.', 'Last Day for Submission of Completion Grades for INC Grades Incurred:', NULL, NULL, NULL, false, false),
  ('cal-2025-2026-011', 'a. 2nd Sem 2023-2024', NULL, 'Table view row', 'deadline', 'Students', 'Official Academic Calendar, School Year 2025-2026.', 'a. 2nd Sem 2023-2024', 'Fri, 15 Aug', NULL, NULL, false, false),
  ('cal-2025-2026-012', 'b. Summer 2024/1st Sem 2024-2025', NULL, 'Table view row', 'deadline', 'Students', 'Official Academic Calendar, School Year 2025-2026.', 'b. Summer 2024/1st Sem 2024-2025', NULL, 'Fri, 30 Jan', NULL, false, false),
  ('cal-2025-2026-013', 'Senior High School Entrance Examination K-12', NULL, 'Table view row', 'event', 'Students', 'Official Academic Calendar, School Year 2025-2026.', 'Senior High School Entrance Examination K-12', NULL, 'Per SHS Schedule', NULL, false, false),
  ('cal-2025-2026-014', 'General Convocation & College Orientation Program', NULL, 'Table view row', 'event', 'MSU community', 'Official Academic Calendar, School Year 2025-2026.', 'General Convocation & College Orientation Program', 'Per DSA Schedule', NULL, NULL, false, false),
  ('cal-2025-2026-015', 'Dissemination of Application for SASE', NULL, 'Table view row', 'event', 'MSU community', 'Official Academic Calendar, School Year 2025-2026.', 'Dissemination of Application for SASE', 'Per OVPAA & Adm. Schedule', NULL, NULL, false, false),
  ('cal-2025-2026-016', '64th MSU Founding Anniversary', NULL, 'Table view row', 'event', 'MSU community', 'Official Academic Calendar, School Year 2025-2026.', '64th MSU Founding Anniversary', 'Mon, 01 Sep', NULL, NULL, false, false),
  ('cal-2025-2026-017', 'Deadline for Submission of Tentative List of Candidates for Graduation (With Evaluation Sheets)', NULL, 'Table view row', 'deadline', 'Students', 'Official Academic Calendar, School Year 2025-2026.', 'Deadline for Submission of Tentative List of Candidates for Graduation (With Evaluation Sheets)', 'Fri, 12 Sep', 'Fri, 27 Feb', NULL, false, false),
  ('cal-2025-2026-018', 'Auto deletion of unconfirmed subjects', NULL, 'Table view row', 'deadline', 'Students', 'Official Academic Calendar, School Year 2025-2026.', 'Auto deletion of unconfirmed subjects', 'Fri, 12 Sep', 'Fri, 27 Feb', NULL, false, false),
  ('cal-2025-2026-019', 'Last Day for Submission of any Appeal from any Graduating Students Regarding Graduation Matters', NULL, 'Table view row', 'deadline', 'Students', 'Official Academic Calendar, School Year 2025-2026.', 'Last Day for Submission of any Appeal from any Graduating Students Regarding Graduation Matters', 'Mon, 15 Sep', 'Mon, 02 Mar', NULL, false, false),
  ('cal-2025-2026-020', 'FIRST PRELIMINARY / DEPARTMENTAL EXAMINATIONS:', NULL, 'Table view row', 'exam', 'Students and faculty', 'Official Academic Calendar, School Year 2025-2026.', 'FIRST PRELIMINARY / DEPARTMENTAL EXAMINATIONS:', NULL, NULL, NULL, false, true),
  ('cal-2025-2026-021', 'a. English', NULL, 'Table view row', 'exam', 'Students and faculty', 'Official Academic Calendar, School Year 2025-2026.', 'a. English', 'Mon, 15 Sep (AM)', 'Mon, 02 Mar (AM)', NULL, false, false),
  ('cal-2025-2026-022', 'b. Philosophy', NULL, 'Table view row', 'exam', 'Students and faculty', 'Official Academic Calendar, School Year 2025-2026.', 'b. Philosophy', 'Mon, 15 Sep (PM)', 'Mon, 02 Mar (PM)', NULL, false, false),
  ('cal-2025-2026-023', 'c. Mathematics', NULL, 'Table view row', 'exam', 'Students and faculty', 'Official Academic Calendar, School Year 2025-2026.', 'c. Mathematics', 'Tue, 16 Sep (Whole Day)', 'Tue, 03 Mar (Whole day)', NULL, false, false),
  ('cal-2025-2026-024', 'd. Physics', NULL, 'Table view row', 'exam', 'Students and faculty', 'Official Academic Calendar, School Year 2025-2026.', 'd. Physics', 'Wed, 17 Sep (AM)', 'Wed, 04 Mar (AM)', NULL, false, false),
  ('cal-2025-2026-025', 'e. All other subjects', NULL, 'Table view row', 'exam', 'Students and faculty', 'Official Academic Calendar, School Year 2025-2026.', 'e. All other subjects', 'Wed, 17 Sep (PM) - Sat, 20 Sep', 'Wed, 04 Mar (PM) - Sat, 07 Mar', NULL, false, false),
  ('cal-2025-2026-026', 'Special Committee of MSU Main Campus Council Meeting', NULL, 'Table view row', 'event', 'MSU community', 'Official Academic Calendar, School Year 2025-2026.', 'Special Committee of MSU Main Campus Council Meeting', 'Wed, 01 Oct', 'Wed, 11 Mar', NULL, true, false),
  ('cal-2025-2026-027', 'Period of Dropping of Subjects', NULL, 'Table view row', 'deadline', 'Students', 'Official Academic Calendar, School Year 2025-2026.', 'Period of Dropping of Subjects', 'Mon, 22 Sep - Fri, 10 Oct', 'Mon, 16 Mar - Fri, 03 Apr', NULL, false, false),
  ('cal-2025-2026-028', 'SSG, College and Department Elections', NULL, 'Table view row', 'event', 'Students', 'Official Academic Calendar, School Year 2025-2026.', 'SSG, College and Department Elections', NULL, NULL, NULL, false, false),
  ('cal-2025-2026-029', 'Removal/Completion Period of Previous INC grades of Graduating Students', NULL, 'Table view row', 'deadline', 'Students', 'Official Academic Calendar, School Year 2025-2026.', 'Removal/Completion Period of Previous INC grades of Graduating Students', 'Mon, 13 Oct - Fri, 17 Oct', 'Mon, 06 Apr - Fri, 10 Apr', NULL, false, false),
  ('cal-2025-2026-030', 'MSU Main Campus Council Meeting', NULL, 'Table view row', 'event', 'MSU community', 'Official Academic Calendar, School Year 2025-2026.', 'MSU Main Campus Council Meeting', 'Wed, 29 Oct', 'Mon, 06 Apr', NULL, true, false),
  ('cal-2025-2026-031', 'MIDTERM / DEPARTMENTAL EXAMINATIONS:', NULL, 'Table view row', 'exam', 'Students and faculty', 'Official Academic Calendar, School Year 2025-2026.', 'MIDTERM / DEPARTMENTAL EXAMINATIONS:', NULL, NULL, 'Wed, 25 Jun - Sat, 27 Jun', false, true),
  ('cal-2025-2026-032', 'a. English', NULL, 'Table view row', 'exam', 'Students and faculty', 'Official Academic Calendar, School Year 2025-2026.', 'a. English', 'Mon, 03 Nov (AM)', 'Mon, 13 Apr (AM)', NULL, false, false),
  ('cal-2025-2026-033', 'b. Philosophy', NULL, 'Table view row', 'exam', 'Students and faculty', 'Official Academic Calendar, School Year 2025-2026.', 'b. Philosophy', 'Mon, 03 Nov (PM)', 'Mon, 13 Apr (PM)', NULL, false, false),
  ('cal-2025-2026-034', 'c. Mathematics', NULL, 'Table view row', 'exam', 'Students and faculty', 'Official Academic Calendar, School Year 2025-2026.', 'c. Mathematics', 'Tue, 04 Nov (Whole Day)', 'Tue, 14 Apr (Whole day)', NULL, false, false),
  ('cal-2025-2026-035', 'd. Chemistry', NULL, 'Table view row', 'exam', 'Students and faculty', 'Official Academic Calendar, School Year 2025-2026.', 'd. Chemistry', 'Wed, 05 Nov (AM)', 'Wed, 15 Apr (AM)', NULL, false, false),
  ('cal-2025-2026-036', 'e. Physics', NULL, 'Table view row', 'exam', 'Students and faculty', 'Official Academic Calendar, School Year 2025-2026.', 'e. Physics', 'Wed, 05 Nov (PM)', 'Wed, 15 Apr (PM)', NULL, false, false),
  ('cal-2025-2026-037', 'f. All Other Subjects', NULL, 'Table view row', 'exam', 'Students and faculty', 'Official Academic Calendar, School Year 2025-2026.', 'f. All Other Subjects', 'Thu, 06 Nov - Sat, 08 Nov', 'Thu, 16 Apr - Sat, 18 Apr', NULL, false, false),
  ('cal-2025-2026-038', 'Last Day for Graduating Students to Clear their Deficiencies other than the Currently Taken Courses', NULL, 'Table view row', 'deadline', 'Students', 'Official Academic Calendar, School Year 2025-2026.', 'Last Day for Graduating Students to Clear their Deficiencies other than the Currently Taken Courses', 'Fri, 07 Nov', 'Fri, 17 Apr', NULL, false, false),
  ('cal-2025-2026-039', 'Submission by Department Chairpersons of Course Offerings for Incoming Semester to ICTC', NULL, 'Table view row', 'deadline', 'Faculty', 'Official Academic Calendar, School Year 2025-2026.', 'Submission by Department Chairpersons of Course Offerings for Incoming Semester to ICTC', 'Mon, 10 Nov - Fri, 14 Nov', NULL, NULL, false, false),
  ('cal-2025-2026-040', 'Pre-enrolment Period for the Next Semester', NULL, 'Table view row', 'enrollment', 'Students', 'Official Academic Calendar, School Year 2025-2026.', 'Pre-enrolment Period for the Next Semester', 'Mon, 17 Nov - Fri, 21 Nov', 'Mon, 27 Apr - Wed, 29 Apr', NULL, false, false),
  ('cal-2025-2026-041', 'Cut-off date of Application for Graduation and Submission of All other Graduation Requirements', NULL, 'Table view row', 'deadline', 'Students', 'Official Academic Calendar, School Year 2025-2026.', 'Cut-off date of Application for Graduation and Submission of All other Graduation Requirements', 'Mon, 17 Nov - Fri, 05 Dec', NULL, NULL, false, false),
  ('cal-2025-2026-042', 'Last day for Filing of Leave of Absence', NULL, 'Table view row', 'deadline', 'Students', 'Official Academic Calendar, School Year 2025-2026.', 'Last day for Filing of Leave of Absence', 'Fri, 21 Nov', 'Fri, 08 May', NULL, false, false),
  ('cal-2025-2026-043', 'MSU System University Council Meeting', NULL, 'Table view row', 'event', 'MSU community', 'Official Academic Calendar, School Year 2025-2026.', 'MSU System University Council Meeting', NULL, NULL, NULL, false, true),
  ('cal-2025-2026-044', 'END OF CLASSES', NULL, 'Table view row', 'classes', 'Students and faculty', 'Official Academic Calendar, School Year 2025-2026.', 'END OF CLASSES', 'Fri, 05 Dec', 'Fri, 22 May', 'Fri, 10 Jul', false, true),
  ('cal-2025-2026-045', 'BOR''s Approval of Candidates for Graduation', NULL, 'Table view row', 'deadline', 'Students', 'Official Academic Calendar, School Year 2025-2026.', 'BOR''s Approval of Candidates for Graduation', 'Per BOR schedule', 'Per BOR schedule', NULL, false, false),
  ('cal-2025-2026-046', 'FINAL / DEPARTMENTAL EXAMINATIONS:', NULL, 'Table view row', 'exam', 'Students and faculty', 'Official Academic Calendar, School Year 2025-2026.', 'FINAL / DEPARTMENTAL EXAMINATIONS:', NULL, NULL, 'Mon, 13 Jul - Fri, 17 Jul', false, true),
  ('cal-2025-2026-047', 'a. English', NULL, 'Table view row', 'exam', 'Students and faculty', 'Official Academic Calendar, School Year 2025-2026.', 'a. English', 'Mon, 15 Dec (AM)', 'Mon, 25 May (AM)', NULL, false, false),
  ('cal-2025-2026-048', 'b. Philosophy', NULL, 'Table view row', 'exam', 'Students and faculty', 'Official Academic Calendar, School Year 2025-2026.', 'b. Philosophy', 'Mon, 15 Dec (PM)', 'Mon, 25 May (PM)', NULL, false, false),
  ('cal-2025-2026-049', 'c. Mathematics', NULL, 'Table view row', 'exam', 'Students and faculty', 'Official Academic Calendar, School Year 2025-2026.', 'c. Mathematics', 'Tue, 16 Dec (Whole Day)', 'Tue, 26 May (Whole Day)', NULL, false, false),
  ('cal-2025-2026-050', 'd. Chemistry', NULL, 'Table view row', 'exam', 'Students and faculty', 'Official Academic Calendar, School Year 2025-2026.', 'd. Chemistry', 'Wed, 17 Dec (AM)', 'Wed, 27 May (AM)', NULL, false, false),
  ('cal-2025-2026-051', 'e. Physics', NULL, 'Table view row', 'exam', 'Students and faculty', 'Official Academic Calendar, School Year 2025-2026.', 'e. Physics', 'Wed, 17 Dec (PM)', 'Wed, 27 May (PM)', NULL, false, false),
  ('cal-2025-2026-052', 'f. All other subjects', NULL, 'Table view row', 'exam', 'Students and faculty', 'Official Academic Calendar, School Year 2025-2026.', 'f. All other subjects', 'Thu, 18 Dec - Sat, 20 Dec', 'Thu, 28 May - Sat, 30 May', NULL, false, false),
  ('cal-2025-2026-053', 'NSTP Graduation', NULL, 'Table view row', 'event', 'Students', 'Official Academic Calendar, School Year 2025-2026.', 'NSTP Graduation', NULL, NULL, NULL, false, false),
  ('cal-2025-2026-054', 'CHRISTMAS VACATION/SEMESTRAL BREAK', NULL, 'Table view row', 'event', 'MSU community', 'Official Academic Calendar, School Year 2025-2026.', 'CHRISTMAS VACATION/SEMESTRAL BREAK', 'Mon, 22 Dec 2025 - Fri, 02 Jan 2026', 'Mon, 01 Jun - Fri, 17 Jul', NULL, false, true),
  ('cal-2025-2026-055', 'Deadline for Submission of Grades:', NULL, 'Table view row', 'deadline', 'Faculty', 'Official Academic Calendar, School Year 2025-2026.', 'Deadline for Submission of Grades:', NULL, NULL, 'Wed, 29 Jul', false, true),
  ('cal-2025-2026-056', 'Graduating', NULL, 'Table view row', 'deadline', 'Faculty', 'Official Academic Calendar, School Year 2025-2026.', 'Graduating', 'Mon, 05 Jan 2026', 'Mon, 08 Jun 2026', NULL, false, false),
  ('cal-2025-2026-057', 'Non-Graduating', NULL, 'Table view row', 'deadline', 'Faculty', 'Official Academic Calendar, School Year 2025-2026.', 'Non-Graduating', 'Fri, 09 Jan 2026', 'Fri, 12 Jun 2026', NULL, false, false),
  ('cal-2025-2026-058', 'Pre-Commencement Exercises', NULL, 'Table view row', 'event', 'MSU community', 'Official Academic Calendar, School Year 2025-2026.', 'Pre-Commencement Exercises', 'Mon, 09 Feb 2026', 'Mon, 27 Jul 2026', NULL, false, false),
  ('cal-2025-2026-059', 'Commencement Proper', NULL, 'Table view row', 'event', 'MSU community', 'Official Academic Calendar, School Year 2025-2026.', 'Commencement Proper', 'Tue, 10 Feb 2026', 'Tue, 28 Jul 2026', NULL, false, false),

  ('cal-2025-2026-900', 'Amun Jadid Holiday', '2025-06-27', 'Fri, 27 Jun 2025', 'event', 'MSU community', 'Holiday and observance from the official Academic Calendar, School Year 2025-2026.', NULL, NULL, NULL, NULL, false, false),
  ('cal-2025-2026-901', 'National Heroes Day', '2025-08-25', 'Mon, 25 Aug 2025', 'event', 'MSU community', 'Holiday and observance from the official Academic Calendar, School Year 2025-2026.', NULL, NULL, NULL, NULL, false, false),
  ('cal-2025-2026-902', 'All Saint''s Day', '2025-11-01', 'Sat, 01 Nov 2025', 'event', 'MSU community', 'Holiday and observance from the official Academic Calendar, School Year 2025-2026.', NULL, NULL, NULL, NULL, false, false),
  ('cal-2025-2026-903', 'Bonifacio Day', '2025-11-30', 'Sun, 30 Nov 2025', 'event', 'MSU community', 'Holiday and observance from the official Academic Calendar, School Year 2025-2026.', NULL, NULL, NULL, NULL, false, false),
  ('cal-2025-2026-904', 'Feast of the Immaculate Conception', '2025-12-08', 'Mon, 08 Dec 2025', 'event', 'MSU community', 'Holiday and observance from the official Academic Calendar, School Year 2025-2026.', NULL, NULL, NULL, NULL, false, false),
  ('cal-2025-2026-905', 'Christmas Day', '2025-12-25', 'Thu, 25 Dec 2025', 'event', 'MSU community', 'Holiday and observance from the official Academic Calendar, School Year 2025-2026.', NULL, NULL, NULL, NULL, false, false),
  ('cal-2025-2026-906', 'Rizal Day', '2025-12-30', 'Tue, 30 Dec 2025', 'event', 'MSU community', 'Holiday and observance from the official Academic Calendar, School Year 2025-2026.', NULL, NULL, NULL, NULL, false, false),
  ('cal-2025-2026-907', 'New Year''s Day', '2026-01-01', 'Thu, 01 Jan 2026', 'event', 'MSU community', 'Holiday and observance from the official Academic Calendar, School Year 2025-2026.', NULL, NULL, NULL, NULL, false, false),
  ('cal-2025-2026-908', 'Maundy Thursday', '2026-04-02', 'Thu, 02 Apr 2026', 'event', 'MSU community', 'Holiday and observance from the official Academic Calendar, School Year 2025-2026.', NULL, NULL, NULL, NULL, false, false),
  ('cal-2025-2026-909', 'Good Friday', '2026-04-03', 'Fri, 03 Apr 2026', 'event', 'MSU community', 'Holiday and observance from the official Academic Calendar, School Year 2025-2026.', NULL, NULL, NULL, NULL, false, false),
  ('cal-2025-2026-910', 'Black Saturday', '2026-04-04', 'Sat, 04 Apr 2026', 'event', 'MSU community', 'Holiday and observance from the official Academic Calendar, School Year 2025-2026.', NULL, NULL, NULL, NULL, false, false),
  ('cal-2025-2026-911', 'Labor Day', '2026-05-01', 'Fri, 01 May 2026', 'event', 'MSU community', 'Holiday and observance from the official Academic Calendar, School Year 2025-2026.', NULL, NULL, NULL, NULL, false, false),
  ('cal-2025-2026-912', 'Independence Day', '2026-06-12', 'Fri, 12 Jun 2026', 'event', 'MSU community', 'Holiday and observance from the official Academic Calendar, School Year 2025-2026.', NULL, NULL, NULL, NULL, false, false)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  event_date = EXCLUDED.event_date,
  date_label = EXCLUDED.date_label,
  type = EXCLUDED.type,
  audience = EXCLUDED.audience,
  details = EXCLUDED.details,
  table_activity = EXCLUDED.table_activity,
  first_semester = EXCLUDED.first_semester,
  second_semester = EXCLUDED.second_semester,
  summer = EXCLUDED.summer,
  table_highlight = EXCLUDED.table_highlight,
  table_section = EXCLUDED.table_section,
  updated_at = now();
